-- ==============================================================================
-- Makkal Kural 2.0 — Central Government Ministries & Representatives Seed Data
-- Union Cabinet Ministers, Central Portfolios, Lok Sabha MPs & CPGRAMS Nodal Authorities
-- ==============================================================================

-- Clean up existing seed data if re-running
DELETE FROM representatives;

INSERT INTO representatives (
  id, name, role, organization, ministry, level, category_specialty, 
  state, district, constituency, parliamentary_constituency, email, x_handle, 
  official_website, source_url, verification_status, last_verified_at, active
) VALUES
-- 1. Prime Minister & Public Grievances
(
  'a0000001-0000-0000-0000-000000000001',
  'Shri Narendra Modi',
  'Prime Minister of India / Minister of Personnel & Public Grievances',
  'Prime Minister''s Office (PMO) & DARPG',
  'Ministry of Personnel, Public Grievances and Pensions',
  'CABINET_MINISTER',
  'all, general administration, central policy, public grievances, national development',
  'Uttar Pradesh',
  'Varanasi',
  'Varanasi',
  'Varanasi',
  'pmo.grievance@gov.in',
  '@PMOIndia',
  'https://www.pmindia.gov.in',
  'https://www.india.gov.in/my-government/prime-ministers-office',
  'VERIFIED',
  NOW(),
  true
),

-- 2. Road Transport and Highways
(
  'a0000001-0000-0000-0000-000000000002',
  'Shri Nitin Gadkari',
  'Union Minister of Road Transport and Highways',
  'Ministry of Road Transport and Highways (MoRTH / NHAI)',
  'Ministry of Road Transport and Highways',
  'CABINET_MINISTER',
  'highways-roads, national highways, expressways, flyovers, toll plaza, nhai, bridges, road safety',
  'Maharashtra',
  'Nagpur',
  'Nagpur',
  'Nagpur',
  'nitin.gadkari@nic.in',
  '@nitin_gadkari',
  'https://morth.nic.in',
  'https://morth.nic.in/who-is-who',
  'VERIFIED',
  NOW(),
  true
),

-- 3. Railways, Information & Broadcasting, Electronics & IT
(
  'a0000001-0000-0000-0000-000000000003',
  'Shri Ashwini Vaishnaw',
  'Union Minister of Railways, Information & Broadcasting, Electronics & IT',
  'Ministry of Railways / MeitY',
  'Ministry of Railways',
  'CABINET_MINISTER',
  'railways, trains, railway stations, pantry food, train delays, electronics, telecom, meity, digital india',
  'All India',
  'National',
  'Rajya Sabha (Odisha)',
  'All India',
  'railgrievance@rb.railnet.gov.in',
  '@AshwiniVaishnaw',
  'https://indianrailways.gov.in',
  'https://indianrailways.gov.in/railwayboard',
  'VERIFIED',
  NOW(),
  true
),

-- 4. Jal Shakti (Drinking Water & Sanitation / River Development)
(
  'a0000001-0000-0000-0000-000000000004',
  'Shri C. R. Patil',
  'Union Minister of Jal Shakti',
  'Ministry of Jal Shakti',
  'Ministry of Jal Shakti',
  'CABINET_MINISTER',
  'water-jal-shakti, jal jeevan mission, drinking water, river cleaning, namami gange, groundwater, canal irrigation',
  'Gujarat',
  'Surat',
  'Navsari',
  'Navsari',
  'minister-jalshakti@gov.in',
  '@CRPaatil',
  'https://jalshakti.gov.in',
  'https://jalshakti.gov.in/en/who-is-who',
  'VERIFIED',
  NOW(),
  true
),

-- 5. Power & Housing and Urban Affairs
(
  'a0000001-0000-0000-0000-000000000005',
  'Shri Manohar Lal Khattar',
  'Union Minister of Housing and Urban Affairs & Minister of Power',
  'Ministry of Housing and Urban Affairs (MoHUA) & Ministry of Power',
  'Ministry of Housing and Urban Affairs',
  'CABINET_MINISTER',
  'urban-housing, power-energy, pmay, smart cities, metro rail, swachh bharat, powergrid, national grid, solar rooftop',
  'Haryana',
  'Karnal',
  'Karnal',
  'Karnal',
  'minister-mohua@gov.in',
  '@mlkhattar',
  'https://mohua.gov.in',
  'https://mohua.gov.in/cms/who-is-who.php',
  'VERIFIED',
  NOW(),
  true
),

-- 6. Communications & Telecom (DoT / India Post)
(
  'a0000001-0000-0000-0000-000000000006',
  'Shri Jyotiraditya Scindia',
  'Union Minister of Communications and Minister of Development of North Eastern Region',
  'Ministry of Communications (DoT / India Post / BSNL)',
  'Ministry of Communications',
  'CABINET_MINISTER',
  'telecom-postal, speed post, india post, bsnl, rural broadband, bharatnet, postal parcel, telecom network',
  'Madhya Pradesh',
  'Guna',
  'Guna',
  'Guna',
  'minister-comm@gov.in',
  '@JM_Scindia',
  'https://dot.gov.in',
  'https://dot.gov.in/whos-who',
  'VERIFIED',
  NOW(),
  true
),

-- 7. Environment, Forest and Climate Change (CPCB)
(
  'a0000001-0000-0000-0000-000000000007',
  'Shri Bhupender Yadav',
  'Union Minister of Environment, Forest and Climate Change',
  'Ministry of Environment, Forest and Climate Change (MoEFCC / CPCB)',
  'Ministry of Environment, Forest and Climate Change',
  'CABINET_MINISTER',
  'environment-pollution, cpcb, industrial emissions, river effluent, deforestation, illegal mining, e-waste, wildlife',
  'Rajasthan',
  'Alwar',
  'Alwar',
  'Alwar',
  'mefcc@gov.in',
  '@byadavbjp',
  'https://moef.gov.in',
  'https://moef.gov.in/en/about-the-ministry/who-is-who/',
  'VERIFIED',
  NOW(),
  true
),

-- 8. Health and Family Welfare & Chemicals and Fertilizers
(
  'a0000001-0000-0000-0000-000000000008',
  'Shri J. P. Nadda',
  'Union Minister of Health and Family Welfare & Chemicals and Fertilizers',
  'Ministry of Health and Family Welfare (MoHFW / AIIMS / NHA)',
  'Ministry of Health and Family Welfare',
  'CABINET_MINISTER',
  'health-welfare, ayushman bharat, pm-jay, aiims hospitals, cghs dispensaries, generic medicines, fssai food adulteration',
  'All India',
  'National',
  'Rajya Sabha (Gujarat)',
  'All India',
  'hfwminister@gov.in',
  '@JPNadda',
  'https://mohfw.gov.in',
  'https://mohfw.gov.in/about-us/who-is-who',
  'VERIFIED',
  NOW(),
  true
),

-- 9. Finance & Corporate Affairs
(
  'a0000001-0000-0000-0000-000000000009',
  'Smt. Nirmala Sitharaman',
  'Union Minister of Finance and Corporate Affairs',
  'Ministry of Finance (CBDT / CBIC / Banking Ombudsman)',
  'Ministry of Finance',
  'CABINET_MINISTER',
  'finance-pension, banking ombudsman, upi fraud, income tax refund, gst portal, epfo, national pension system, central taxes',
  'All India',
  'National',
  'Rajya Sabha (Karnataka)',
  'All India',
  'appointment.fm@gov.in',
  '@nsitharaman',
  'https://finmin.nic.in',
  'https://finmin.nic.in/whos-who',
  'VERIFIED',
  NOW(),
  true
),

-- 10. Consumer Affairs, Food and Public Distribution
(
  'a0000001-0000-0000-0000-000000000010',
  'Shri Pralhad Joshi',
  'Union Minister of Consumer Affairs, Food and Public Distribution & New and Renewable Energy',
  'Ministry of Consumer Affairs, Food and Public Distribution / MNRE',
  'Ministry of Consumer Affairs, Food and Public Distribution',
  'CABINET_MINISTER',
  'consumer-civil-supplies, national consumer helpline, nfsa food grains, e-commerce fraud, misleading ads, solar subsidy',
  'Karnataka',
  'Dharwad',
  'Dharwad',
  'Dharwad',
  'minister.ca@nic.in',
  '@JoshiPralhad',
  'https://consumeraffairs.nic.in',
  'https://consumeraffairs.nic.in/whos-who',
  'VERIFIED',
  NOW(),
  true
),

-- 11. Civil Aviation
(
  'a0000001-0000-0000-0000-000000000011',
  'Shri Kinjarapu Rammohan Naidu',
  'Union Minister of Civil Aviation',
  'Ministry of Civil Aviation (DGCA / AAI / AirSewa)',
  'Ministry of Civil Aviation',
  'CABINET_MINISTER',
  'civil-aviation, airsewa, airline refund, airport infrastructure, luggage delay, flight cancellation, udan',
  'Andhra Pradesh',
  'Srikakulam',
  'Srikakulam',
  'Srikakulam',
  'minister.moca@nic.in',
  '@RamMNK',
  'https://www.civilaviation.gov.in',
  'https://www.civilaviation.gov.in/whos-who',
  'VERIFIED',
  NOW(),
  true
),

-- 12. Agriculture and Farmers Welfare & Rural Development
(
  'a0000001-0000-0000-0000-000000000012',
  'Shri Shivraj Singh Chouhan',
  'Union Minister of Agriculture and Farmers Welfare & Minister of Rural Development',
  'Ministry of Agriculture & Ministry of Rural Development',
  'Ministry of Agriculture and Farmers Welfare',
  'CABINET_MINISTER',
  'agriculture-rural, pm-kisan, pmgsy rural roads, crop insurance pmfby, fertilizer supply, mgnrega rural wages',
  'Madhya Pradesh',
  'Vidisha',
  'Vidisha',
  'Vidisha',
  'agri.minister@gov.in',
  '@ChouhanShivraj',
  'https://agricoop.gov.in',
  'https://agricoop.gov.in/en/who-is-who',
  'VERIFIED',
  NOW(),
  true
),

-- 13. Central Public Grievance Portal Officer (CPGRAMS / DARPG)
(
  'a0000001-0000-0000-0000-000000000013',
  'Secretary, DARPG / CPGRAMS Nodal Cell',
  'Director General / Central Public Grievances Officer',
  'Department of Administrative Reforms and Public Grievances (DARPG)',
  'Ministry of Personnel, Public Grievances and Pensions',
  'CENTRAL_AGENCY',
  'all, cpgrams, general civic grievances, central escalation, administrative reform',
  'Delhi',
  'New Delhi',
  'New Delhi',
  'New Delhi',
  'cpgrams-grievance@nic.in',
  '@DARPG_GoI',
  'https://pgportal.gov.in',
  'https://darpg.gov.in/whos-who',
  'VERIFIED',
  NOW(),
  true
),

-- 14. Key Lok Sabha MPs (Delhi, Tamil Nadu, Maharashtra, Karnataka, Uttar Pradesh, Telangana, West Bengal)
(
  'a0000001-0000-0000-0000-000000000014',
  'Smt. Bansuri Swaraj',
  'Member of Parliament (Lok Sabha)',
  'Parliament of India (Lok Sabha)',
  'Lok Sabha Secretariat',
  'LOK_SABHA_MP',
  'all, new delhi local grievance, municipal, mp lad fund, public amenities',
  'Delhi',
  'New Delhi',
  'New Delhi',
  'New Delhi',
  'bansuri.swaraj.mp@sansad.nic.in',
  '@BansuriSwaraj',
  'https://sansad.in/ls',
  'https://sansad.in/ls/members',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000015',
  'Dr. Kalanidhi Veeraswamy',
  'Member of Parliament (Lok Sabha)',
  'Parliament of India (Lok Sabha)',
  'Lok Sabha Secretariat',
  'LOK_SABHA_MP',
  'all, chennai north local grievance, coastal roads, ports, municipal water, drainage',
  'Tamil Nadu',
  'Chennai',
  'Chennai North',
  'Chennai North',
  'kalanidhi.v.mp@sansad.nic.in',
  '@KalanidhiV',
  'https://sansad.in/ls',
  'https://sansad.in/ls/members',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000016',
  'Smt. Thamizhachi Thangapandian',
  'Member of Parliament (Lok Sabha)',
  'Parliament of India (Lok Sabha)',
  'Lok Sabha Secretariat',
  'LOK_SABHA_MP',
  'all, chennai south local grievance, it corridor, omr highway, velachery metro, urban amenities',
  'Tamil Nadu',
  'Chennai',
  'Chennai South',
  'Chennai South',
  'thamizhachi.mp@sansad.nic.in',
  '@ThamizhachiTh',
  'https://sansad.in/ls',
  'https://sansad.in/ls/members',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000017',
  'Shri Tejasvi Surya',
  'Member of Parliament (Lok Sabha)',
  'Parliament of India (Lok Sabha)',
  'Lok Sabha Secretariat',
  'LOK_SABHA_MP',
  'all, bangalore south local grievance, bengaluru metro, suburban rail, urban traffic, digital tech',
  'Karnataka',
  'Bengaluru Urban',
  'Bangalore South',
  'Bangalore South',
  'tejasvi.surya.mp@sansad.nic.in',
  '@Tejasvi_Surya',
  'https://sansad.in/ls',
  'https://sansad.in/ls/members',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000018',
  'Shri Arvind Sawant',
  'Member of Parliament (Lok Sabha)',
  'Parliament of India (Lok Sabha)',
  'Lok Sabha Secretariat',
  'LOK_SABHA_MP',
  'all, mumbai south local grievance, port trust, coastal road, railway terminus, municipal amenities',
  'Maharashtra',
  'Mumbai City',
  'Mumbai South',
  'Mumbai South',
  'arvind.sawant.mp@sansad.nic.in',
  '@AGSawant',
  'https://sansad.in/ls',
  'https://sansad.in/ls/members',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000019',
  'Shri Asaduddin Owaisi',
  'Member of Parliament (Lok Sabha)',
  'Parliament of India (Lok Sabha)',
  'Lok Sabha Secretariat',
  'LOK_SABHA_MP',
  'all, hyderabad local grievance, old city drainage, heritage preservation, municipal power, water',
  'Telangana',
  'Hyderabad',
  'Hyderabad',
  'Hyderabad',
  'asad.owaisi.mp@sansad.nic.in',
  '@asadowaisi',
  'https://sansad.in/ls',
  'https://sansad.in/ls/members',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000020',
  'Shri Rajnath Singh',
  'Union Minister of Defence & MP (Lok Sabha)',
  'Ministry of Defence & Lok Sabha',
  'Ministry of Defence',
  'CABINET_MINISTER',
  'all, lucknow local grievance, defence estates, cantt roads, national infrastructure',
  'Uttar Pradesh',
  'Lucknow',
  'Lucknow',
  'Lucknow',
  'rajnath.singh@sansad.nic.in',
  '@rajnathsingh',
  'https://www.mod.gov.in',
  'https://sansad.in/ls/members',
  'VERIFIED',
  NOW(),
  true
);
