export interface CivicCategory {
  id: string;
  nameEn: string;
  nameTa: string;
  nameHi: string;
  ministryEn: string;
  ministryTa: string;
  ministryHi: string;
  icon: string;
  descriptionEn: string;
  descriptionTa: string;
  descriptionHi: string;
  subcategoriesEn: string[];
  subcategoriesTa: string[];
  subcategoriesHi: string[];
}

export const CIVIC_CATEGORIES: CivicCategory[] = [
  {
    id: 'highways-roads',
    nameEn: 'National Highways & Expressways',
    nameTa: 'தேசிய நெடுஞ்சாலைகள் & விரைவுச்சாலைகள்',
    nameHi: 'राष्ट्रीय राजमार्ग एवं एक्सप्रेसवे',
    ministryEn: 'Ministry of Road Transport and Highways (MoRTH / NHAI)',
    ministryTa: 'சாலை போக்குவரத்து மற்றும் நெடுஞ்சாலைகள் அமைச்சகம்',
    ministryHi: 'सड़क परिवहन एवं राजमार्ग मंत्रालय (MoRTH / NHAI)',
    icon: 'Road',
    descriptionEn: 'National highway damage, toll plaza irregularities, missing signages, expressway safety, flyovers',
    descriptionTa: 'தேசிய நெடுஞ்சாலை சேதங்கள், சுங்கச்சாவடி புகார்கள், எச்சரிக்கை பலகைகள், மேம்பாலங்கள்',
    descriptionHi: 'राष्ट्रीय राजमार्ग क्षति, टोल प्लाजा अनियमितताएं, संकेतक, एक्सप्रेसवे सुरक्षा',
    subcategoriesEn: ['National Highway Potholes / Damage', 'Toll Plaza Overcharging / Fastag Issue', 'Missing Highway Signboards & Lights', 'Flyover / Bridge Structural Issue', 'Highway Encroachment & Illegal Cuts'],
    subcategoriesTa: ['தேசிய நெடுஞ்சாலை குழிகள்', 'சுங்கச்சாவடி / பாஸ்டேக் பிரச்சனை', 'நெடுஞ்சாலை பலகைகள் & விளக்குகள்', 'மேம்பாலம் / பாலம் பிரச்சனை', 'நெடுஞ்சாலை ஆக்கிரமிப்பு'],
    subcategoriesHi: ['राष्ट्रीय राजमार्ग गड्ढे / क्षति', 'टोल प्लाजा फास्टैग समस्या', 'राजमार्ग संकेतक एवं रोशनी', 'फ्लाईओवर संरचनात्मक समस्या', 'राजमार्ग अतिक्रमण'],
  },
  {
    id: 'railways',
    nameEn: 'Indian Railways & Trains',
    nameTa: 'இந்திய ரயில்வே & ரயில் சேவைகள்',
    nameHi: 'भारतीय रेल एवं रेल सेवाएं',
    ministryEn: 'Ministry of Railways (Railway Board)',
    ministryTa: 'ரயில்வே அமைச்சகம்',
    ministryHi: 'रेल मंत्रालय (रेलवे बोर्ड)',
    icon: 'Train',
    descriptionEn: 'Train delays, coach cleanliness, railway station facilities, ticket grievances, pantry food quality',
    descriptionTa: 'ரயில் தாமதம், பெட்டிகள் தூய்மை, ரயில் நிலைய வசதிகள், டிக்கெட் புகார்கள், உணவு தரம்',
    descriptionHi: 'ट्रेन में देरी, कोच की स्वच्छता, रेलवे स्टेशन सुविधाएं, टिकट संबंधी शिकायतें, खानपान',
    subcategoriesEn: ['Coach Cleanliness & Bio-Toilet Issue', 'Train Delay & Unannounced Rescheduling', 'Railway Station Amenities & Accessibility', 'Pantry Food Quality & Overcharging', 'Security / Passenger Safety in Train'],
    subcategoriesTa: ['ரயில் பெட்டி & கழிப்பறை தூய்மை', 'ரயில் தாமதம்', 'ரயில் நிலைய வசதிகள்', 'உணவு தரம் மற்றும் கூடுதல் கட்டணம்', 'பயணிகள் பாதுகாப்பு'],
    subcategoriesHi: ['कोच स्वच्छता एवं बायो-टॉयलेट', 'ट्रेन में देरी एवं समय सारिणी', 'रेलवे स्टेशन सुविधाएं', 'खानपान गुणवत्ता एवं अधिक मूल्य', 'यात्री सुरक्षा'],
  },
  {
    id: 'water-jal-shakti',
    nameEn: 'Water Resources & Drinking Water',
    nameTa: 'நீர் வளம் & ஜல் ஜீவன் குடிநீர்',
    nameHi: 'जल संसाधन एवं जल जीवन मिशन',
    ministryEn: 'Ministry of Jal Shakti (Drinking Water & Sanitation)',
    ministryTa: 'ஜல் சக்தி அமைச்சகம்',
    ministryHi: 'जल शक्ति मंत्रालय (पेयजल एवं स्वच्छता)',
    icon: 'Droplets',
    descriptionEn: 'Jal Jeevan Mission piped water supply, inter-state water issues, river pollution, groundwater contamination',
    descriptionTa: 'ஜல் ஜீவன் குடிநீர் விநியோகம், ஆற்று நீர் மாசுபாடு, நிலத்தடி நீர் பிரச்சனை',
    descriptionHi: 'जल जीवन मिशन नल का पानी, अंतर्राज्यीय जल मुद्दे, नदी प्रदूषण, भूजल स्वच्छता',
    subcategoriesEn: ['Jal Jeevan Mission Tap Water Supply', 'River / Lake Pollution & Sewage Dumping', 'Groundwater Depletion & Industrial Waste', 'Canal Irrigation & Water Flow Defect', 'Drinking Water Quality Testing'],
    subcategoriesTa: ['ஜல் ஜீவன் குழாய் குடிநீர்', 'ஆற்று நீர் மாசுபாடு', 'நிலத்தடி நீர் கழிவு', 'பாசனக் கால்வாய் பிரச்சனை', 'குடிநீர் தரப் பரிசோதனை'],
    subcategoriesHi: ['जल जीवन मिशन नल जल आपूर्ति', 'नदी/झील प्रदूषण', 'भूजल प्रदूषण एवं औद्योगिक अपशिष्ट', 'नहर सिंचाई एवं जल प्रवाह', 'पेयजल गुणवत्ता'],
  },
  {
    id: 'power-energy',
    nameEn: 'National Power Grid & Energy',
    nameTa: 'தேசிய மின்கட்டமைப்பு & புதுப்பிக்கத்தக்க ஆற்றல்',
    nameHi: 'राष्ट्रीय पावर ग्रिड एवं नवीकरणीय ऊर्जा',
    ministryEn: 'Ministry of Power & MNRE (PowerGrid / REC)',
    ministryTa: 'மின்சாரம் மற்றும் புதிய எரிசக்தி அமைச்சகம்',
    ministryHi: 'विद्युत मंत्रालय एवं नवीन और नवीकरणीय ऊर्जा मंत्रालय',
    icon: 'Zap',
    descriptionEn: 'Inter-state grid transmission, PM Surya Ghar solar rooftop subsidy, rural electrification, tariff disputes',
    descriptionTa: 'சூரிய ஒளி மின்சார மானியம், மின்கட்டமைப்பு, கிராமப்புற மின்மயமாக்கல்',
    descriptionHi: 'राष्ट्रीय ग्रिड ट्रांसमिशन, पीएम सूर्य घर रूफटॉप सोलर सब्सिडी, ग्रामीण विद्युतीकरण',
    subcategoriesEn: ['PM Surya Ghar Solar Rooftop Subsidy Delay', 'High-Tension Transmission Line Hazard', 'Rural Electrification Network Defect', 'Renewable Energy Grid Connection', 'National Power Tariff Discrepancy'],
    subcategoriesTa: ['சூரிய ஒளி கூரை மின்சார மானிய தாமதம்', 'உயர் மின்னழுத்த கம்பிகள் ஆபத்து', 'கிராம மின் இணைப்பு கோளாறு', 'புதுப்பிக்கத்தக்க ஆற்றல் இணைப்பு', 'மின் கட்டண முரண்பாடு'],
    subcategoriesHi: ['पीएम सूर्य घर सोलर सब्सिडी', 'हाई-टेंशन ट्रांसमिशन लाइन खतरा', 'ग्रामीण विद्युतीकरण नेटवर्क', 'नवीकरणीय ऊर्जा ग्रिड कनेक्टिविटी', 'विद्युत टैरिफ विसंगति'],
  },
  {
    id: 'urban-housing',
    nameEn: 'Urban Development & Housing (PMAY / Smart Cities)',
    nameTa: 'நகர்ப்புற வளர்ச்சி & வீட்டுவசதி (PMAY)',
    nameHi: 'आवासन एवं शहरी कार्य (PMAY / स्मार्ट सिटी)',
    ministryEn: 'Ministry of Housing and Urban Affairs (MoHUA)',
    ministryTa: 'வீட்டுவசதி மற்றும் நகர்ப்புற விவகாரங்கள் அமைச்சகம்',
    ministryHi: 'आवासन और शहरी कार्य मंत्रालय (MoHUA)',
    icon: 'Building2',
    descriptionEn: 'Pradhan Mantri Awas Yojana (PMAY) house allocation, Smart City projects, Metro rail, Swachh Bharat mission',
    descriptionTa: 'பிரதமர் வீட்டுவசதி திட்டம் (PMAY), ஸ்மார்ட் சிட்டி பணிகள், மெட்ரோ ரயில், தூய்மை பாரதம்',
    descriptionHi: 'पीएम आवास योजना (PMAY), स्मार्ट सिटी परियोजनाएं, मेट्रो रेल, स्वच्छ भारत मिशन',
    subcategoriesEn: ['PMAY Urban / Rural House Sanction & Subsidy', 'Smart City Construction Stoppage / Corruption', 'Metro Rail Station & Connectivity Issue', 'Swachh Bharat Solid Waste Facility Defect', 'National Urban Drainage & Flood Mitigation'],
    subcategoriesTa: ['PMAY வீட்டு மானிய அனுமதி', 'ஸ்மார்ட் சிட்டி திட்ட தாமதம்', 'மெட்ரோ ரயில் இணைப்பு', 'தூய்மை பாரத கழிவு வசதி', 'நகர்ப்புற வெள்ள வடிகால்'],
    subcategoriesHi: ['पीएम आवास योजना सब्सिडी', 'स्मार्ट सिटी निर्माण में देरी', 'मेट्रो रेल कनेक्टिविटी', 'स्वच्छ भारत अपशिष्ट प्रबंधन', 'शहरी जल निकासी एवं बाढ़ नियंत्रण'],
  },
  {
    id: 'telecom-postal',
    nameEn: 'Telecom, Postal & Digital Public Services',
    nameTa: 'தொலைத்தொடர்பு, அஞ்சல் & டிஜிட்டல் சேவைகள்',
    nameHi: 'दूरसंचार, डाक एवं डिजिटल सार्वजनिक सेवाएं',
    ministryEn: 'Ministry of Communications & MeitY (DoT / India Post)',
    ministryTa: 'தகவல் தொடர்பு மற்றும் தகவல் தொழில்நுட்ப அமைச்சகம்',
    ministryHi: 'संचार मंत्रालय एवं इलेक्ट्रॉनिकी और आईटी मंत्रालय (DoT / India Post / MeitY)',
    icon: 'Radio',
    descriptionEn: 'BSNL/MTNL network issues, India Post parcel delays, Speed Post tracking, cyber fraud, broadband connectivity',
    descriptionTa: 'பிஎஸ்என்எல் சேவை, அஞ்சல் பார்சல் தாமதம், ஸ்பீட் போஸ்ட், இணைய இணைப்பு',
    descriptionHi: 'बीएसएनएल नेटवर्क, भारतीय डाक पार्सल विलंब, स्पीड पोस्ट ट्रैकिंग, ब्रॉडबैंड कनेक्टिविटी, साइबर सुरक्षा',
    subcategoriesEn: ['India Post / Speed Post Missing Parcel', 'BharatNet Rural Broadband Connectivity', 'BSNL / MTNL Network Outage & Service Quality', 'Cyber Crime & Online Financial Fraud Routing', 'Digital Identity / Aadhaar Seva Kendra Issue'],
    subcategoriesTa: ['அஞ்சல் / ஸ்பீட் போஸ்ட் பார்சல் தாமதம்', 'பாரத்நெட் இணைய சேவை', 'பிஎஸ்என்எல் நெட்வொர்க் கோளாறு', 'சைபர் குற்றப் புகார்', 'ஆதார் சேவை மையம் பிரச்சனை'],
    subcategoriesHi: ['स्पीड पोस्ट / पार्सल विलंब', 'भारतनेट ब्रॉडबैंड कनेक्टिविटी', 'बीएसएनएल नेटवर्क आउटेज', 'साइबर धोखाधड़ी शिकायत', 'आधार सेवा केंद्र समस्या'],
  },
  {
    id: 'environment-pollution',
    nameEn: 'Environment, Forests & Pollution Control',
    nameTa: 'சுற்றுச்சூழல், காடுகள் & மாசுக் கட்டுப்பாடு',
    nameHi: 'पर्यावरण, वन एवं जलवायु परिवर्तन',
    ministryEn: 'Ministry of Environment, Forest and Climate Change (MoEFCC / CPCB)',
    ministryTa: 'சுற்றுச்சூழல் மற்றும் வனத்துறை அமைச்சகம்',
    ministryHi: 'पर्यावरण, वन और जलवायु परिवर्तन मंत्रालय (MoEFCC / CPCB)',
    icon: 'Trees',
    descriptionEn: 'Industrial air/water pollution, Central Pollution Control Board violations, illegal forest deforestation, wildlife protection',
    descriptionTa: 'தொழிற்சாலை காற்று/நீர் மாசுபாடு, மத்திய மாசுக் கட்டுப்பாடு, காடுகள் அழிப்பு, வனவிலங்கு பாதுகாப்பு',
    descriptionHi: 'औद्योगिक वायु एवं जल प्रदूषण, केंद्रीय प्रदूषण नियंत्रण बोर्ड उल्लंघन, अवैध वन कटाई, वन्यजीव संरक्षण',
    subcategoriesEn: ['CPCB Industrial Air / Chimney Emission Violation', 'Industrial Toxic Effluent in Rivers', 'Illegal Deforestation / Eco-Sensitive Encroachment', 'Hazardous & E-Waste Dumping Violations', 'Wildlife Conflict & National Park Buffer Issue'],
    subcategoriesTa: ['தொழிற்சாலை காற்று மாசுபாடு', 'ஆற்றில் நச்சுக் கழிவு வெளியேற்றம்', 'சட்டவிரோத காடழிப்பு', 'மின்னணுக் கழிவுகள் கொட்டுதல்', 'வனவிலங்கு பாதுகாப்பு'],
    subcategoriesHi: ['सीपीसीबी औद्योगिक उत्सर्जन उल्लंघन', 'नदियों में जहरीला औद्योगिक कचरा', 'अवैध वनों की कटाई', 'ई-कचरा डंपिंग', 'वन्यजीव संरक्षण'],
  },
  {
    id: 'health-welfare',
    nameEn: 'National Health & Central Hospitals (AIIMS / CGHS)',
    nameTa: 'தேசிய நல்வாழ்வு & மத்திய மருத்துவமனைகள் (AIIMS)',
    nameHi: 'स्वास्थ्य एवं परिवार कल्याण (एम्स / सीजीएचएस / आयुष्मान भारत)',
    ministryEn: 'Ministry of Health and Family Welfare (MoHFW / NHA)',
    ministryTa: 'சுகாதாரம் மற்றும் குடும்ப நல அமைச்சகம்',
    ministryHi: 'स्वास्थ्य एवं परिवार कल्याण मंत्रालय (MoHFW / NHA)',
    icon: 'Cross',
    descriptionEn: 'Ayushman Bharat PM-JAY card denial, AIIMS hospital queues & facilities, CGHS dispensary medicine shortages',
    descriptionTa: 'ஆயுஷ்மான் பாரத் கார்டு மறுப்பு, எய்ம்ஸ் மருத்துவமனை வசதிகள், சி.ஜி.எச்.எஸ் மருந்து தட்டுப்பாடு',
    descriptionHi: 'आयुष्मान भारत पीएम-जय कार्ड अस्वीकृति, एम्स अस्पताल सुविधाएं, सीजीएचएस औषधालय दवा कमी',
    subcategoriesEn: ['Ayushman Bharat (PM-JAY) Empanelled Hospital Refusal', 'AIIMS / Central Hospital Appointment & Diagnostic Delay', 'CGHS Dispensary Essential Medicine Shortage', 'Jan Aushadhi Kendra Generic Drug Availability', 'Food Safety & Standards Authority (FSSAI) Adulteration'],
    subcategoriesTa: ['ஆயுஷ்மான் பாரத் சிகிச்சை மறுப்பு', 'எய்ம்ஸ் மருத்துவமனை தாமதம்', 'சி.ஜி.எச்.எஸ் மருந்து தட்டுப்பாடு', 'ஜன் ஔஷதி பொது மருந்தகம்', 'உணவு பாதுகாப்பு மற்றும் தரம்'],
    subcategoriesHi: ['आयुष्मान भारत अस्पताल इनकार', 'एम्स अस्पताल अपॉइंटमेंट विलंब', 'सीजीएचएस आवश्यक दवाओं की कमी', 'जन औषधि केंद्र जेनेरिक दवाएं', 'एफएसएसएआई खाद्य मिलावट'],
  },
  {
    id: 'finance-pension',
    nameEn: 'Banking, EPFO, Pension & Central Taxes',
    nameTa: 'வங்கி, வருங்கால வைப்பு நிதி (EPFO), ஓய்வூதியம் & வரிகள்',
    nameHi: 'बैंकिंग, ईपीएफओ, पेंशन एवं केंद्रीय कर (CBDT / CBIC)',
    ministryEn: 'Ministry of Finance & Ministry of Labour (EPFO / RBI Ombudsman)',
    ministryTa: 'நிதி அமைச்சகம் மற்றும் தொழிலாளர் அமைச்சகம்',
    ministryHi: 'वित्त मंत्रालय एवं श्रम और रोजगार मंत्रालय (EPFO / RBI ओंबुड्समैन)',
    icon: 'Coins',
    descriptionEn: 'EPFO provident fund withdrawal delays, Banking Ombudsman grievances, Central pension (NPS) issues, Income Tax/GST refunds',
    descriptionTa: 'வருங்கால வைப்பு நிதி (EPF) பணம் பெறுவதில் தாமதம், வங்கி குறைதீர்ப்பு, ஓய்வூதியம் (NPS), ஜிஎஸ்டி ரீபண்ட்',
    descriptionHi: 'ईपीएफओ पीएफ निकासी में देरी, बैंकिंग लोकपाल, राष्ट्रीय पेंशन प्रणाली (NPS), आयकर/जीएसटी रिफंड',
    subcategoriesEn: ['EPFO PF Claim Rejection / Settlement Delay', 'Banking Ombudsman / ATM & UPI Fraud Redressal', 'Central Pension Accounting (CPAO / SPARSH / NPS) Grievance', 'Income Tax / GST Refund Processing Delay', 'Insurance Ombudsman Claim Dispute'],
    subcategoriesTa: ['இபிஎப் பணப்பலன் தாமதம்', 'வங்கி குறைதீர்ப்பு மற்றும் யுபிஐ புகார்', 'மத்திய அரசு ஓய்வூதிய குறை', 'வருமான வரி / ஜிஎஸ்டி ரீபண்ட் தாமதம்', 'காப்பீட்டு குறைதீர்ப்பு'],
    subcategoriesHi: ['ईपीएफओ दावा निपटान में देरी', 'बैंकिंग लोकपाल एवं यूपीआई धोखाधड़ी', 'केंद्रीय पेंशन प्रणाली (NPS / SPARSH)', 'आयकर / जीएसटी रिफंड विलंब', 'बीमा लोकपाल दावा विवाद'],
  },
  {
    id: 'consumer-civil-supplies',
    nameEn: 'Consumer Affairs & National Food Security (NFSA)',
    nameTa: 'நுகர்வோர் பாதுகாப்பு & தேசிய உணவுப் பாதுகாப்பு',
    nameHi: 'उपभोक्ता मामले एवं राष्ट्रीय खाद्य सुरक्षा (NFSA / FCI)',
    ministryEn: 'Ministry of Consumer Affairs, Food and Public Distribution',
    ministryTa: 'நுகர்வோர் விவகாரங்கள் மற்றும் உணவு அமைச்சகம்',
    ministryHi: 'उपभोक्ता मामले, खाद्य और सार्वजनिक वितरण मंत्रालय',
    icon: 'ShoppingBag',
    descriptionEn: 'National Consumer Helpline escalation, E-commerce misleading ads & return fraud, NFSA ration allocation, FCI grain storage',
    descriptionTa: 'நுகர்வோர் குறைதீர்ப்பு, இணையதள வர்த்தக ஏமாற்று, ரேஷன் பொருட்கள் ஒதுக்கீடு',
    descriptionHi: 'राष्ट्रीय उपभोक्ता हेल्पलाइन, ई-कॉमर्स भ्रामक विज्ञापन, राष्ट्रीय खाद्य सुरक्षा राशन आवंटन, एफसीआई',
    subcategoriesEn: ['E-Commerce Dark Patterns & Refund Fraud Escalation', 'Misleading Advertisements & Consumer Rights Violation', 'NFSA Central Food Grain Stock & Ration Fair Price Defect', 'Weights & Measures Inaccuracy / MRP Overcharging', 'Packaged Commodities Standards Non-Compliance'],
    subcategoriesTa: ['இணையதள வர்த்தக ஏமாற்று மற்றும் ரீபண்ட்', 'தவறான விளம்பரங்கள் புகார்', 'தேசிய உணவுப் பாதுகாப்பு தானிய விநியோகம்', 'அளவீடு மற்றும் கூடுதல் விலை', 'பாக்கெட் பொருட்கள் விதிமீறல்'],
    subcategoriesHi: ['ई-कॉमर्स रिफंड धोखाधड़ी', 'भ्रामक विज्ञापन उपभोक्ता अधिकार', 'एनएफएसए राशन वितरण समस्या', 'माप-तौल एवं एमआरपी उल्लंघन', 'पैकेज्ड उत्पाद मानक'],
  },
  {
    id: 'civil-aviation',
    nameEn: 'Civil Aviation & Airports (AAI / DGCA)',
    nameTa: 'விமானப் போக்குவரத்து & விமான நிலையங்கள் (AAI)',
    nameHi: 'नागर विमानन एवं हवाई अड्डे (DGCA / AAI)',
    ministryEn: 'Ministry of Civil Aviation (Airports Authority of India)',
    ministryTa: 'விமானப் போக்குவரத்து அமைச்சகம்',
    ministryHi: 'नागर विमानन मंत्रालय (भारतीय विमानपत्तन प्राधिकरण / DGCA)',
    icon: 'Plane',
    descriptionEn: 'Airport infrastructure, Flight cancellation refunds (AirSewa), Luggage loss, DGCA safety violations',
    descriptionTa: 'விமான நிலைய வசதிகள், விமான ரத்து கட்டண ரீபண்ட், உடமைகள் இழப்பு, பாதுகாப்பு விதிகள்',
    descriptionHi: 'हवाई अड्डा बुनियादी ढांचा, उड़ान रद्दीकरण रिफंड (एयरसेवा), बैगेज नुकसान, डीजीसीए सुरक्षा',
    subcategoriesEn: ['AirSewa Airline Ticket Refund Refusal', 'Airport Passenger Accessibility & Baggage Misplacement', 'Flight Delay Without Passenger Care', 'UDAN Regional Connectivity Route Non-Operation', 'Aviation Safety & Tariff Overcharging'],
    subcategoriesTa: ['விமான டிக்கெட் ரீபண்ட் மறுப்பு', 'விமான நிலைய உடமைகள் இழப்பு', 'விமான தாமதப் பராமரிப்பு இன்மை', 'உதான் திட்ட விமான சேவை', 'விமானப் பயணக் கட்டணக் கொள்ளை'],
    subcategoriesHi: ['एयरसेवा टिकट रिफंड अस्वीकृति', 'हवाई अड्डा बैगेज एवं पहुंच समस्या', 'उड़ान में देरी और यात्री सुविधा', 'उड़ान क्षेत्रीय कनेक्टिविटी', 'विमानन किराया विसंगति'],
  },
  {
    id: 'agriculture-rural',
    nameEn: 'Agriculture, PM-KISAN & Rural Infrastructure',
    nameTa: 'வேளாண்மை, PM-கிசான் & ஊரக வளர்ச்சி',
    nameHi: 'कृषि, पीएम-किसान एवं ग्रामीण विकास (PMGSY)',
    ministryEn: 'Ministry of Agriculture & Ministry of Rural Development',
    ministryTa: 'வேளாண்மை மற்றும் ஊரக வளர்ச்சி அமைச்சகம்',
    ministryHi: 'कृषि एवं किसान कल्याण मंत्रालय एवं ग्रामीण विकास मंत्रालय',
    icon: 'Wheat',
    descriptionEn: 'PM-KISAN Samman Nidhi installment delay, PMGSY rural road construction, Crop insurance (PMFBY), Fertilizer availability',
    descriptionTa: 'பிஎம் கிசான் நிதி தாமதம், பிரதமரின் கிராம சாலை திட்டம், பயிர்க் காப்பீடு, உரத் தட்டுப்பாடு',
    descriptionHi: 'पीएम-किसान सम्मान निधि किस्त विलंब, पीएमजीएसवाई ग्रामीण सड़कें, फसल बीमा (PMFBY), उर्वरक उपलब्धता',
    subcategoriesEn: ['PM-KISAN DBT Installment Non-Credit', 'Pradhan Mantri Gram Sadak Yojana (PMGSY) Road Defect', 'Pradhan Mantri Fasal Bima Yojana (PMFBY) Crop Loss Claim', 'Urea & Fertilizer Distribution Black-Marketing', 'MGNREGA National Wage Payment Delay'],
    subcategoriesTa: ['பிஎம் கிசான் நிதி விடுவிப்பு தாமதம்', 'கிராம சாலை திட்டம் (PMGSY) சேதம்', 'பயிர்க் காப்பீட்டுத் தொகை (PMFBY)', 'உரத் தட்டுப்பாடு மற்றும் கூடுதல் விலை', '100 நாள் வேலை திட்ட ஊதியத் தாமதம்'],
    subcategoriesHi: ['पीएम-किसान किस्त प्राप्त न होना', 'पीएम ग्राम सड़क योजना (PMGSY) क्षति', 'पीएम फसल बीमा योजना (PMFBY) दावा', 'उर्वरक एवं खाद कालाबाजारी', 'मनरेगा मजदूरी भुगतान विलंब'],
  },
];

export function getCategoryById(id: string): CivicCategory | undefined {
  return CIVIC_CATEGORIES.find(c => c.id === id);
}

export function getAllCategories(): CivicCategory[] {
  return CIVIC_CATEGORIES;
}
