import {
  BusFleetItem,
  RoadDefectItem,
  TrafficIntelligenceData,
  OriginDestinationFlow,
  IncidentRecord,
  ANPRItem,
  RoutePerformanceItem,
  EdgeAIModelItem,
  MaintenancePriorityItem,
} from '@/types/urban-intelligence';

export const INITIAL_BUS_FLEET: BusFleetItem[] = [
  {
    id: 'bus-mtc-1042',
    busNumber: 'TN-01-N-9421',
    routeCode: '21G',
    routeName: 'Broadway ⇄ Tambaram',
    depot: 'Central Depot / T. Nagar',
    driverName: 'R. Kathirvel',
    lat: 13.0418,
    lng: 80.2341,
    speedKmH: 28,
    headingDeg: 195,
    status: 'ONLINE',
    cameras: {
      front: 'ACTIVE',
      rear: 'ACTIVE',
      leftSide: 'ACTIVE',
      rightSide: 'ACTIVE',
      cabin: 'ACTIVE',
    },
    edgeAI: {
      status: 'ACTIVE',
      model: 'YOLOv11-Edge-Mobility (INT8)',
      fps: 32.4,
      gpuTempC: 58.2,
      npuUsagePct: 74,
      bandwidthSavedPct: 98.6,
      eventsProcessedToday: 1420,
    },
    lastEvent: {
      type: 'POTHOLE_DETECTED',
      time: 'Just now',
      confidence: 94.2,
    },
    connectivity: '5G_HIGH',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'bus-mtc-1088',
    busNumber: 'TN-01-N-8820',
    routeCode: '570',
    routeName: 'CMBT ⇄ Siruseri IT Park (OMR)',
    depot: 'Koyambedu / Adyar',
    driverName: 'S. Munusamy',
    lat: 12.9864,
    lng: 80.2425,
    speedKmH: 34,
    headingDeg: 160,
    status: 'ONLINE',
    cameras: {
      front: 'ACTIVE',
      rear: 'ACTIVE',
      leftSide: 'ACTIVE',
      rightSide: 'ACTIVE',
      cabin: 'ACTIVE',
    },
    edgeAI: {
      status: 'ACTIVE',
      model: 'YOLOv11-Edge-Mobility (INT8)',
      fps: 31.8,
      gpuTempC: 61.0,
      npuUsagePct: 81,
      bandwidthSavedPct: 98.4,
      eventsProcessedToday: 1890,
    },
    lastEvent: {
      type: 'DANGEROUS_OVERTAKE',
      time: '3 min ago',
      confidence: 91.5,
    },
    connectivity: '5G_HIGH',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'bus-mtc-1134',
    busNumber: 'TN-01-N-7734',
    routeCode: '19B',
    routeName: 'T. Nagar ⇄ Kelambakkam',
    depot: 'Saidapet Depot',
    driverName: 'M. Jayakumar',
    lat: 13.0034,
    lng: 80.2014,
    speedKmH: 22,
    headingDeg: 210,
    status: 'ONLINE',
    cameras: {
      front: 'ACTIVE',
      rear: 'ACTIVE',
      leftSide: 'ACTIVE',
      rightSide: 'DEGRADED',
      cabin: 'ACTIVE',
    },
    edgeAI: {
      status: 'ACTIVE',
      model: 'YOLOv11-Edge-Mobility (INT8)',
      fps: 29.5,
      gpuTempC: 56.4,
      npuUsagePct: 68,
      bandwidthSavedPct: 99.1,
      eventsProcessedToday: 1150,
    },
    lastEvent: {
      type: 'WATERLOGGING_CLUSTER',
      time: '8 min ago',
      confidence: 89.8,
    },
    connectivity: '4G_STABLE',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'bus-mtc-1205',
    busNumber: 'TN-01-N-6512',
    routeCode: '29C',
    routeName: 'Perambur ⇄ Besant Nagar',
    depot: 'Mandaiveli Depot',
    driverName: 'P. Anandhan',
    lat: 13.0827,
    lng: 80.2707,
    speedKmH: 19,
    headingDeg: 120,
    status: 'ONLINE',
    cameras: {
      front: 'ACTIVE',
      rear: 'ACTIVE',
      leftSide: 'ACTIVE',
      rightSide: 'ACTIVE',
      cabin: 'ACTIVE',
    },
    edgeAI: {
      status: 'ACTIVE',
      model: 'YOLOv11-Edge-Mobility (INT8)',
      fps: 33.1,
      gpuTempC: 59.8,
      npuUsagePct: 76,
      bandwidthSavedPct: 98.7,
      eventsProcessedToday: 1640,
    },
    lastEvent: {
      type: 'MISSING_ZEBRA_CROSSING',
      time: '14 min ago',
      confidence: 93.1,
    },
    connectivity: '5G_HIGH',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'bus-mtc-1322',
    busNumber: 'TN-01-N-5544',
    routeCode: '102',
    routeName: 'Broadway ⇄ Kelambakkam',
    depot: 'Thiruvanmiyur Depot',
    driverName: 'K. Balaji',
    lat: 12.9249,
    lng: 80.1000,
    speedKmH: 42,
    headingDeg: 45,
    status: 'ONLINE',
    cameras: {
      front: 'ACTIVE',
      rear: 'ACTIVE',
      leftSide: 'ACTIVE',
      rightSide: 'ACTIVE',
      cabin: 'ACTIVE',
    },
    edgeAI: {
      status: 'ACTIVE',
      model: 'YOLOv11-Edge-Mobility (INT8)',
      fps: 30.2,
      gpuTempC: 54.1,
      npuUsagePct: 72,
      bandwidthSavedPct: 98.9,
      eventsProcessedToday: 980,
    },
    lastEvent: {
      type: 'DAMAGED_SIGN_BOARD',
      time: '22 min ago',
      confidence: 88.4,
    },
    connectivity: '5G_HIGH',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'bus-mtc-1450',
    busNumber: 'TN-01-N-3310',
    routeCode: '47D',
    routeName: 'Avadi ⇄ Thiruvanmiyur',
    depot: 'Ambattur Depot',
    driverName: 'V. Sundaram',
    lat: 13.0880,
    lng: 80.1650,
    speedKmH: 0,
    headingDeg: 0,
    status: 'IDLE',
    cameras: {
      front: 'ACTIVE',
      rear: 'ACTIVE',
      leftSide: 'OFFLINE',
      rightSide: 'ACTIVE',
      cabin: 'ACTIVE',
    },
    edgeAI: {
      status: 'STANDBY',
      model: 'YOLOv11-Edge-Mobility (INT8)',
      fps: 0,
      gpuTempC: 44.0,
      npuUsagePct: 5,
      bandwidthSavedPct: 100,
      eventsProcessedToday: 820,
    },
    connectivity: '4G_STABLE',
    lastUpdated: new Date().toISOString(),
  },
];

export const INITIAL_ROAD_DEFECTS: RoadDefectItem[] = [
  {
    id: 'def-1042-pot-01',
    defectType: 'POTHOLE',
    title: 'Severe crater defect on Anna Salai (Near Nandanam Signal)',
    confidence: 95.8,
    severity: 'HIGH',
    status: 'VERIFIED',
    lat: 13.0289,
    lng: 80.2312,
    locality: 'Anna Salai, Nandanam Junction',
    district: 'Chennai',
    state: 'Tamil Nadu',
    busId: 'MTC-1042',
    busRoute: '21G',
    cameraPosition: 'FRONT',
    timestamp: '2026-09-28T09:42:10Z',
    repeatedDetections: 6,
    busesInvolved: ['MTC-1042', 'MTC-1134', 'MTC-1088', 'MTC-1205'],
    evidenceImageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=600&q=80',
    boundingBox: { x: 38, y: 58, width: 24, height: 18 },
    ministryJurisdiction: 'State Highways & Greater Chennai Corporation (GCC)',
  },
  {
    id: 'def-1088-wat-02',
    defectType: 'WATERLOGGING',
    title: 'Heavy waterlogging on OMR Express corridor near Perungudi Toll',
    confidence: 92.4,
    severity: 'CRITICAL',
    status: 'DETECTED',
    lat: 12.9648,
    lng: 80.2444,
    locality: 'Old Mahabalipuram Road (OMR), Perungudi',
    district: 'Chennai',
    state: 'Tamil Nadu',
    busId: 'MTC-1088',
    busRoute: '570',
    cameraPosition: 'FRONT',
    timestamp: '2026-09-28T09:15:22Z',
    repeatedDetections: 4,
    busesInvolved: ['MTC-1088', 'MTC-1322'],
    evidenceImageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80',
    boundingBox: { x: 20, y: 45, width: 60, height: 35 },
    ministryJurisdiction: 'Ministry of Road Transport and Highways / GCC Stormwater',
  },
  {
    id: 'def-1134-div-03',
    defectType: 'MISSING_DIVIDER',
    title: 'Displaced concrete median divider hazard on GST Road near Guindy',
    confidence: 89.1,
    severity: 'CRITICAL',
    status: 'VERIFIED',
    lat: 13.0067,
    lng: 80.2023,
    locality: 'GST Road, Guindy Flyover descent',
    district: 'Chennai',
    state: 'Tamil Nadu',
    busId: 'MTC-1134',
    busRoute: '19B',
    cameraPosition: 'RIGHT',
    timestamp: '2026-09-28T08:55:40Z',
    repeatedDetections: 5,
    busesInvolved: ['MTC-1134', 'MTC-1042', 'MTC-1205'],
    evidenceImageUrl: 'https://images.unsplash.com/photo-1508873696983-2df570464756?auto=format&fit=crop&w=600&q=80',
    boundingBox: { x: 50, y: 40, width: 20, height: 30 },
    ministryJurisdiction: 'National Highways Authority of India (NHAI)',
  },
  {
    id: 'def-1205-zeb-04',
    defectType: 'MISSING_ZEBRA_CROSSING',
    title: 'Faded pedestrian zebra crossing in front of Lady Willingdon School',
    confidence: 94.6,
    severity: 'MEDIUM',
    status: 'DETECTED',
    lat: 13.0520,
    lng: 80.2800,
    locality: 'Kamarajar Salai, Marina Beach corridor',
    district: 'Chennai',
    state: 'Tamil Nadu',
    busId: 'MTC-1205',
    busRoute: '29C',
    cameraPosition: 'FRONT',
    timestamp: '2026-09-28T08:30:15Z',
    repeatedDetections: 3,
    busesInvolved: ['MTC-1205', 'MTC-1042'],
    evidenceImageUrl: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=600&q=80',
    boundingBox: { x: 30, y: 70, width: 40, height: 20 },
    ministryJurisdiction: 'Traffic Police & Municipal Corporation',
  },
  {
    id: 'def-1322-sgn-05',
    defectType: 'DAMAGED_TRAFFIC_SIGN',
    title: 'Damaged overhead speed limit and lane guidance board',
    confidence: 91.0,
    severity: 'LOW',
    status: 'DETECTED',
    lat: 12.9200,
    lng: 80.2200,
    locality: 'East Coast Road (ECR), Sholinganallur Link',
    district: 'Chennai',
    state: 'Tamil Nadu',
    busId: 'MTC-1322',
    busRoute: '102',
    cameraPosition: 'FRONT',
    timestamp: '2026-09-28T08:12:00Z',
    repeatedDetections: 2,
    busesInvolved: ['MTC-1322'],
    evidenceImageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80',
    boundingBox: { x: 65, y: 15, width: 25, height: 25 },
    ministryJurisdiction: 'State Highways Department',
  },
];

export const INITIAL_TRAFFIC_DATA: TrafficIntelligenceData[] = [
  {
    corridorId: 'corr-anna-salai',
    corridorName: 'Anna Salai Arterial Corridor (Saidapet → Gemini)',
    lat: 13.0350,
    lng: 80.2390,
    vehiclesCount: {
      cars: 142,
      bikes: 320,
      buses: 18,
      trucks: 4,
      autos: 64,
      pedestrians: 85,
    },
    totalCount: 633,
    densityIndex: 84,
    avgSpeedKmH: 18,
    congestionLevel: 'HEAVY',
    flowRateVehiclesPerMin: 126,
    bottleneckAlert: 'Traffic bottleneck near Nandanam Metro station due to lane restriction',
    timestamp: new Date().toISOString(),
  },
  {
    corridorId: 'corr-omr-it-corridor',
    corridorName: 'OMR IT Expressway (SRP Tools → Sholinganallur)',
    lat: 12.9600,
    lng: 80.2450,
    vehiclesCount: {
      cars: 210,
      bikes: 450,
      buses: 26,
      trucks: 12,
      autos: 45,
      pedestrians: 40,
    },
    totalCount: 783,
    densityIndex: 78,
    avgSpeedKmH: 26,
    congestionLevel: 'MODERATE',
    flowRateVehiclesPerMin: 145,
    timestamp: new Date().toISOString(),
  },
  {
    corridorId: 'corr-gst-airport',
    corridorName: 'GST Road (Guindy ⇄ Chennai Airport)',
    lat: 12.9900,
    lng: 80.1800,
    vehiclesCount: {
      cars: 180,
      bikes: 290,
      buses: 22,
      trucks: 18,
      autos: 70,
      pedestrians: 30,
    },
    totalCount: 610,
    densityIndex: 91,
    avgSpeedKmH: 14,
    congestionLevel: 'SEVERE_BOTTLENECK',
    flowRateVehiclesPerMin: 98,
    bottleneckAlert: 'Severe gridlock at Kathipara interchange junction descent',
    timestamp: new Date().toISOString(),
  },
  {
    corridorId: 'corr-evr-periyar',
    corridorName: 'EVR Periyar Salai (Poonamallee High Road)',
    lat: 13.0780,
    lng: 80.2500,
    vehiclesCount: {
      cars: 95,
      bikes: 210,
      buses: 14,
      trucks: 6,
      autos: 38,
      pedestrians: 60,
    },
    totalCount: 423,
    densityIndex: 52,
    avgSpeedKmH: 36,
    congestionLevel: 'FREE_FLOW',
    flowRateVehiclesPerMin: 85,
    timestamp: new Date().toISOString(),
  },
];

export const INITIAL_OD_FLOWS: OriginDestinationFlow[] = [
  {
    id: 'od-1',
    origin: 'Guindy Junction',
    destination: 'T. Nagar (Panagal Park)',
    peakPeriod: '08:30 AM - 10:30 AM',
    volumePerHour: 4850,
    avgTravelTimeMin: 38,
    expectedTimeMin: 18,
    delayMin: 20,
    congestionIndex: 88,
  },
  {
    id: 'od-2',
    origin: 'Chennai Airport / Meenambakkam',
    destination: 'Guindy Industrial Estate',
    peakPeriod: '09:00 AM - 11:00 AM',
    volumePerHour: 6200,
    avgTravelTimeMin: 34,
    expectedTimeMin: 16,
    delayMin: 18,
    congestionIndex: 92,
  },
  {
    id: 'od-3',
    origin: 'Anna Nagar Roundtana',
    destination: 'Chennai Central Station',
    peakPeriod: '08:00 AM - 10:00 AM',
    volumePerHour: 3900,
    avgTravelTimeMin: 29,
    expectedTimeMin: 20,
    delayMin: 9,
    congestionIndex: 64,
  },
  {
    id: 'od-4',
    origin: 'Adyar (Lattice Bridge)',
    destination: 'T. Nagar (Usman Road)',
    peakPeriod: '05:30 PM - 08:30 PM',
    volumePerHour: 5100,
    avgTravelTimeMin: 42,
    expectedTimeMin: 22,
    delayMin: 20,
    congestionIndex: 86,
  },
  {
    id: 'od-5',
    origin: 'Tambaram Sanatorium',
    destination: 'Siruseri IT Park (OMR)',
    peakPeriod: '08:30 AM - 10:30 AM',
    volumePerHour: 4400,
    avgTravelTimeMin: 49,
    expectedTimeMin: 30,
    delayMin: 19,
    congestionIndex: 81,
  },
];

export const INITIAL_INCIDENTS: IncidentRecord[] = [
  {
    id: 'inc-2026-0891',
    type: 'RASH_DRIVING',
    title: 'High-speed reckless overtaking cutting across bus lane near Guindy',
    timestamp: '2026-09-28T09:28:14Z',
    lat: 13.0102,
    lng: 80.2084,
    locality: 'GST Road near Guindy Metro',
    district: 'Chennai',
    busId: 'MTC-1042',
    busRoute: '21G',
    cameraPosition: 'FRONT',
    vehicleType: 'Sedan (White)',
    vehicleMakeModel: 'Hyundai Verna',
    vehicleColor: 'Polar White',
    licensePlate: 'TN 09 AB 1234',
    ocrConfidence: 94.8,
    trackingId: 'TRK-8812',
    speedRecordedKmH: 78,
    confidence: 96.2,
    severity: 'HIGH',
    status: 'FLAGGED',
    evidenceClipPlaceholder: '/mock-clips/incident-01.mp4',
    vehicleCropUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=400&q=80',
    plateCropUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=300&q=80',
    description: 'Vehicle recorded cutting aggressively across front bumper of bus at 78 km/h in a 40 km/h transit priority corridor.',
  },
  {
    id: 'inc-2026-0892',
    type: 'SCHOOL_ZONE_ALERT',
    title: 'Speeding commercial mini-truck in active school pedestrian crossing zone',
    timestamp: '2026-09-28T08:45:00Z',
    lat: 13.0480,
    lng: 80.2410,
    locality: 'Cathedral Road near Stella Maris',
    district: 'Chennai',
    busId: 'MTC-1205',
    busRoute: '29C',
    cameraPosition: 'FRONT',
    vehicleType: 'Mini Truck (Yellow)',
    vehicleMakeModel: 'Tata Ace',
    vehicleColor: 'Commercial Yellow',
    licensePlate: 'TN 02 CC 9871',
    ocrConfidence: 91.2,
    trackingId: 'TRK-8804',
    speedRecordedKmH: 52,
    confidence: 93.4,
    severity: 'CRITICAL',
    status: 'INVESTIGATING',
    evidenceClipPlaceholder: '/mock-clips/incident-02.mp4',
    vehicleCropUrl: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=400&q=80',
    description: 'Vehicle failed to yield to crossing schoolchildren; emergency braking triggered on edge-AI collision hazard detector.',
  },
  {
    id: 'inc-2026-0893',
    type: 'HIT_AND_RUN',
    title: 'Two-wheeler struck by speeding SUV; offender failed to stop',
    timestamp: '2026-09-28T07:15:30Z',
    lat: 12.9800,
    lng: 80.2450,
    locality: 'OMR Expressway near Thoraipakkam Junction',
    district: 'Chennai',
    busId: 'MTC-1088',
    busRoute: '570',
    cameraPosition: 'LEFT',
    vehicleType: 'SUV (Dark Grey)',
    vehicleMakeModel: 'Mahindra Scorpio-N',
    vehicleColor: 'Dark Grey',
    licensePlate: 'TN 14 BE 5542',
    ocrConfidence: 89.6,
    trackingId: 'TRK-8789',
    speedRecordedKmH: 84,
    confidence: 97.5,
    severity: 'CRITICAL',
    status: 'DISPATCHED_POLICE',
    evidenceClipPlaceholder: '/mock-clips/incident-03.mp4',
    vehicleCropUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=400&q=80',
    description: 'Side-impact collision with motorcycle recorded by Bus 1088 left-camera. Full 8-second buffered evidence package & ANPR cropped frame dispatched to Greater Chennai Traffic Police.',
  },
];

export const INITIAL_ANPR_RECORDS: ANPRItem[] = [
  {
    id: 'anpr-01',
    licensePlate: 'TN 09 AB 1234',
    vehicleType: 'Sedan',
    makeModel: 'Hyundai Verna',
    color: 'White',
    ocrConfidence: 94.8,
    timestamp: '2026-09-28T09:28:14Z',
    lat: 13.0102,
    lng: 80.2084,
    locality: 'GST Road, Guindy',
    busId: 'MTC-1042',
    speedKmH: 78,
    violationFlag: 'Rash Driving & Bus Lane Breach',
  },
  {
    id: 'anpr-02',
    licensePlate: 'TN 02 CC 9871',
    vehicleType: 'Commercial Mini-Truck',
    makeModel: 'Tata Ace',
    color: 'Yellow',
    ocrConfidence: 91.2,
    timestamp: '2026-09-28T08:45:00Z',
    lat: 13.0480,
    lng: 80.2410,
    locality: 'Cathedral Road',
    busId: 'MTC-1205',
    speedKmH: 52,
    violationFlag: 'School Zone Overspeeding',
  },
  {
    id: 'anpr-03',
    licensePlate: 'TN 14 BE 5542',
    vehicleType: 'SUV',
    makeModel: 'Mahindra Scorpio-N',
    color: 'Grey',
    ocrConfidence: 89.6,
    timestamp: '2026-09-28T07:15:30Z',
    lat: 12.9800,
    lng: 80.2450,
    locality: 'OMR Thoraipakkam',
    busId: 'MTC-1088',
    speedKmH: 84,
    violationFlag: 'Hit & Run Collision',
  },
  {
    id: 'anpr-04',
    licensePlate: 'TN 07 AX 3390',
    vehicleType: 'Hatchback',
    makeModel: 'Maruti Swift',
    color: 'Red',
    ocrConfidence: 96.1,
    timestamp: '2026-09-28T09:12:00Z',
    lat: 13.0350,
    lng: 80.2390,
    locality: 'Anna Salai, Teynampet',
    busId: 'MTC-1042',
    speedKmH: 34,
  },
  {
    id: 'anpr-05',
    licensePlate: 'TN 22 DK 7711',
    vehicleType: 'Motorcycle',
    makeModel: 'Royal Enfield Classic',
    color: 'Black',
    ocrConfidence: 88.3,
    timestamp: '2026-09-28T08:58:12Z',
    lat: 12.9648,
    lng: 80.2444,
    locality: 'OMR Perungudi',
    busId: 'MTC-1088',
    speedKmH: 48,
    violationFlag: 'Helmet Non-Compliance Detected',
  },
];

export const INITIAL_ROUTE_PERFORMANCE: RoutePerformanceItem[] = [
  {
    routeCode: '21G',
    routeName: 'Broadway ⇄ Tambaram',
    totalBuses: 24,
    origin: 'Broadway Bus Terminus',
    destination: 'Tambaram Sanatorium',
    lengthKm: 32.4,
    expectedDurationMin: 48,
    currentAvgDurationMin: 68,
    delayMin: 20,
    avgSpeedKmH: 19.2,
    congestionStatus: 'HEAVY_CONGESTION',
    frequentBottlenecks: ['Kathipara Junction', 'Nandanam Signal', 'Chromepet Bridge'],
    reliabilityScore: 68,
  },
  {
    routeCode: '570',
    routeName: 'CMBT ⇄ Siruseri IT Park',
    totalBuses: 32,
    origin: 'Koyambedu (CMBT)',
    destination: 'Siruseri IT Park (OMR)',
    lengthKm: 38.6,
    expectedDurationMin: 55,
    currentAvgDurationMin: 72,
    delayMin: 17,
    avgSpeedKmH: 24.5,
    congestionStatus: 'MODERATE_DELAY',
    frequentBottlenecks: ['SRP Tools Junction', 'Thoraipakkam Toll', 'Sholinganallur'],
    reliabilityScore: 74,
  },
  {
    routeCode: '19B',
    routeName: 'T. Nagar ⇄ Kelambakkam',
    totalBuses: 18,
    origin: 'T. Nagar Terminus',
    destination: 'Kelambakkam',
    lengthKm: 34.0,
    expectedDurationMin: 50,
    currentAvgDurationMin: 64,
    delayMin: 14,
    avgSpeedKmH: 22.8,
    congestionStatus: 'MODERATE_DELAY',
    frequentBottlenecks: ['Saidapet Bridge', 'Guindy Metro', 'Medavakkam'],
    reliabilityScore: 78,
  },
  {
    routeCode: '29C',
    routeName: 'Perambur ⇄ Besant Nagar',
    totalBuses: 16,
    origin: 'Perambur Railway Station',
    destination: 'Besant Nagar Beach',
    lengthKm: 18.2,
    expectedDurationMin: 35,
    currentAvgDurationMin: 39,
    delayMin: 4,
    avgSpeedKmH: 28.0,
    congestionStatus: 'NORMAL',
    frequentBottlenecks: ['Chetpet Signal'],
    reliabilityScore: 92,
  },
];

export const INITIAL_EDGE_MODELS: EdgeAIModelItem[] = [
  {
    id: 'model-road-defect',
    name: 'Road Defect & Hazard Detector (YOLOv11-Defect)',
    category: 'Infrastructure & Safety',
    framework: 'TensorRT / ONNX (INT8 Quantized)',
    status: 'ONLINE',
    confidenceThresholdPct: 85,
    fps: 30,
    detectionsToday: 842,
    lastInferenceTime: '12ms (Edge NPU)',
    memoryMb: 320,
    description: 'Detects potholes, severe asphalt cracks, waterlogging, broken lane dividers, and missing zebra crossings in real-time.',
  },
  {
    id: 'model-traffic-density',
    name: 'Multi-Class Vehicle & Pedestrian Counter',
    category: 'Traffic Flow & Density',
    framework: 'YOLOv11-Nano + ByteTrack',
    status: 'ONLINE',
    confidenceThresholdPct: 80,
    fps: 32,
    detectionsToday: 48900,
    lastInferenceTime: '8ms (Edge NPU)',
    memoryMb: 240,
    description: 'Categorizes 6 vehicle classes + pedestrians to calculate lane density and congestion indices on the fly.',
  },
  {
    id: 'model-incident-safety',
    name: 'Rash Driving & Collision Near-Miss Predictor',
    category: 'Incident & Safety Alerts',
    framework: 'Spatial-Temporal Transformer (Edge)',
    status: 'ONLINE',
    confidenceThresholdPct: 88,
    fps: 28,
    detectionsToday: 38,
    lastInferenceTime: '18ms (Edge GPU)',
    memoryMb: 410,
    description: 'Analyzes trajectory vectors to flag sudden near-miss collisions, pedestrian cut-offs, and hit-and-run situations.',
  },
  {
    id: 'model-anpr-ocr',
    name: 'High-Speed License Plate Reader (ANPR / CRNN)',
    category: 'Law Enforcement & Tracking',
    framework: 'LPRNet + CRNN OCR',
    status: 'ONLINE',
    confidenceThresholdPct: 85,
    fps: 25,
    detectionsToday: 1240,
    lastInferenceTime: '15ms (Edge NPU)',
    memoryMb: 190,
    description: 'High accuracy license plate localization and character recognition for vehicles involved in safety violations.',
  },
];

export const INITIAL_MAINTENANCE_ITEMS: MaintenancePriorityItem[] = [
  {
    id: 'maint-pothole-nandanam',
    defectId: 'def-1042-pot-01',
    title: 'Pothole Cluster #P-1042 (Anna Salai, Nandanam)',
    defectType: 'POTHOLE',
    locality: 'Anna Salai, Nandanam Signal Junction',
    district: 'Chennai',
    lat: 13.0289,
    lng: 80.2312,
    severity: 'HIGH',
    detectionFrequency: 6,
    busesReporting: ['MTC-1042', 'MTC-1134', 'MTC-1088', 'MTC-1205'],
    firstDetectedAt: '2026-09-28T06:15:00Z',
    lastDetectedAt: '2026-09-28T09:42:10Z',
    affectedBusRoutes: ['21G', '19B', '570', '18D', 'A51'],
    nearbyBusVolumeDaily: 480,
    suggestedPriorityScore: 94,
    recommendedAction: 'Emergency Cold-Mix Patchwork & Milling by GCC Division 141',
    status: 'ACTION_REQUIRED',
  },
  {
    id: 'maint-waterlog-perungudi',
    defectId: 'def-1088-wat-02',
    title: 'Severe Waterlogging #W-2099 (OMR Perungudi Toll)',
    defectType: 'WATERLOGGING',
    locality: 'OMR Express Corridor, Perungudi',
    district: 'Chennai',
    lat: 12.9648,
    lng: 80.2444,
    severity: 'CRITICAL',
    detectionFrequency: 4,
    busesReporting: ['MTC-1088', 'MTC-1322'],
    firstDetectedAt: '2026-09-28T07:10:00Z',
    lastDetectedAt: '2026-09-28T09:15:22Z',
    affectedBusRoutes: ['570', '102', '19D', 'AC-570'],
    nearbyBusVolumeDaily: 620,
    suggestedPriorityScore: 98,
    recommendedAction: 'Deploy High-Power Dewatering Sump Pump & Clear Stormwater Drain Choke',
    status: 'ACTION_REQUIRED',
  },
  {
    id: 'maint-divider-guindy',
    defectId: 'def-1134-div-03',
    title: 'Displaced Concrete Divider #D-1134 (Guindy Flyover)',
    defectType: 'MISSING_DIVIDER',
    locality: 'GST Road, Guindy Flyover descent',
    district: 'Chennai',
    lat: 13.0067,
    lng: 80.2023,
    severity: 'CRITICAL',
    detectionFrequency: 5,
    busesReporting: ['MTC-1134', 'MTC-1042', 'MTC-1205'],
    firstDetectedAt: '2026-09-28T05:30:00Z',
    lastDetectedAt: '2026-09-28T08:55:40Z',
    affectedBusRoutes: ['19B', '21G', '70V', 'G18'],
    nearbyBusVolumeDaily: 750,
    suggestedPriorityScore: 96,
    recommendedAction: 'NHAI Crane Dispatch to Re-align Concrete Median & Bolt Reflective Hazard Markers',
    status: 'ACTION_REQUIRED',
  },
];
