-- ==============================================================================
-- Makkal Kural 2.0 — Seed Data Migration
-- Migration: 20260818000003_seed_data.sql
-- ==============================================================================

DELETE FROM representatives;

INSERT INTO representatives (
  id, name, role, organization, ministry, level, category_specialty, 
  state, district, constituency, parliamentary_constituency, email, x_handle, 
  official_website, source_url, verification_status, last_verified_at, active
) VALUES
(
  'a0000001-0000-0000-0000-000000000001',
  'Shri Narendra Modi',
  'Prime Minister of India / Minister of Personnel & Public Grievances',
  'Prime Minister''s Office (PMO) & DARPG',
  'Ministry of Personnel, Public Grievances and Pensions',
  'CABINET_MINISTER',
  'all, general administration, central policy, public grievances, national development',
  'Uttar Pradesh',
  'Varanasi',
  'Varanasi',
  'Varanasi',
  'pmo.grievance@gov.in',
  '@PMOIndia',
  'https://www.pmindia.gov.in',
  'https://www.india.gov.in/my-government/prime-ministers-office',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000002',
  'Shri Nitin Gadkari',
  'Union Minister of Road Transport and Highways',
  'Ministry of Road Transport and Highways (MoRTH / NHAI)',
  'Ministry of Road Transport and Highways',
  'CABINET_MINISTER',
  'highways-roads, national highways, expressways, flyovers, toll plaza, nhai, bridges, road safety',
  'Maharashtra',
  'Nagpur',
  'Nagpur',
  'Nagpur',
  'nitin.gadkari@nic.in',
  '@nitin_gadkari',
  'https://morth.nic.in',
  'https://morth.nic.in/who-is-who',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000003',
  'Shri Ashwini Vaishnaw',
  'Union Minister of Railways, Information & Broadcasting, Electronics & IT',
  'Ministry of Railways / MeitY',
  'Ministry of Railways',
  'CABINET_MINISTER',
  'railways, trains, railway stations, pantry food, train delays, electronics, telecom, meity, digital india',
  'All India',
  'National',
  'Rajya Sabha (Odisha)',
  'All India',
  'railgrievance@rb.railnet.gov.in',
  '@AshwiniVaishnaw',
  'https://indianrailways.gov.in',
  'https://indianrailways.gov.in/railwayboard',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000004',
  'Shri C. R. Patil',
  'Union Minister of Jal Shakti',
  'Ministry of Jal Shakti',
  'Ministry of Jal Shakti',
  'CABINET_MINISTER',
  'water-jal-shakti, jal jeevan mission, drinking water, river cleaning, namami gange, groundwater, canal irrigation',
  'Gujarat',
  'Surat',
  'Navsari',
  'Navsari',
  'minister-jalshakti@gov.in',
  '@CRPaatil',
  'https://jalshakti.gov.in',
  'https://jalshakti.gov.in/en/who-is-who',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000005',
  'Shri Manohar Lal Khattar',
  'Union Minister of Housing and Urban Affairs & Minister of Power',
  'Ministry of Housing and Urban Affairs (MoHUA) & Ministry of Power',
  'Ministry of Housing and Urban Affairs',
  'CABINET_MINISTER',
  'urban-housing, power-energy, pmay, smart cities, metro rail, swachh bharat, powergrid, national grid, solar rooftop',
  'Haryana',
  'Karnal',
  'Karnal',
  'Karnal',
  'minister-mohua@gov.in',
  '@mlkhattar',
  'https://mohua.gov.in',
  'https://mohua.gov.in/cms/who-is-who.php',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000006',
  'Shri Jyotiraditya Scindia',
  'Union Minister of Communications and Minister of DoNER',
  'Ministry of Communications (DoT / India Post / BSNL)',
  'Ministry of Communications',
  'CABINET_MINISTER',
  'telecom-postal, speed post, india post, bsnl, rural broadband, bharatnet, postal parcel, telecom network',
  'Madhya Pradesh',
  'Guna',
  'Guna',
  'Guna',
  'minister-comm@gov.in',
  '@JM_Scindia',
  'https://dot.gov.in',
  'https://dot.gov.in/whos-who',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000007',
  'Shri Bhupender Yadav',
  'Union Minister of Environment, Forest and Climate Change',
  'Ministry of Environment, Forest and Climate Change (MoEFCC / CPCB)',
  'Ministry of Environment, Forest and Climate Change',
  'CABINET_MINISTER',
  'environment-pollution, cpcb, industrial emissions, river effluent, deforestation, illegal mining, e-waste, wildlife',
  'Rajasthan',
  'Alwar',
  'Alwar',
  'Alwar',
  'mefcc@gov.in',
  '@byadavbjp',
  'https://moef.gov.in',
  'https://moef.gov.in/en/about-the-ministry/who-is-who/',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000008',
  'Shri J. P. Nadda',
  'Union Minister of Health and Family Welfare & Chemicals and Fertilizers',
  'Ministry of Health and Family Welfare (MoHFW / AIIMS / NHA)',
  'Ministry of Health and Family Welfare',
  'CABINET_MINISTER',
  'health-welfare, ayushman bharat, pm-jay, aiims hospitals, cghs dispensaries, generic medicines, fssai food adulteration',
  'All India',
  'National',
  'Rajya Sabha (Gujarat)',
  'All India',
  'hfwminister@gov.in',
  '@JPNadda',
  'https://mohfw.gov.in',
  'https://mohfw.gov.in/about-us/who-is-who',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000009',
  'Smt. Nirmala Sitharaman',
  'Union Minister of Finance and Corporate Affairs',
  'Ministry of Finance (CBDT / CBIC / Banking Ombudsman)',
  'Ministry of Finance',
  'CABINET_MINISTER',
  'finance-pension, banking ombudsman, upi fraud, income tax refund, gst portal, epfo, national pension system, central taxes',
  'All India',
  'National',
  'Rajya Sabha (Karnataka)',
  'All India',
  'appointment.fm@gov.in',
  '@nsitharaman',
  'https://finmin.nic.in',
  'https://finmin.nic.in/whos-who',
  'VERIFIED',
  NOW(),
  true
),
(
  'a0000001-0000-0000-0000-000000000010',
  'Secretary, DARPG / CPGRAMS Nodal Cell',
  'Director General / Central Public Grievances Officer',
  'Department of Administrative Reforms and Public Grievances (DARPG)',
  'Ministry of Personnel, Public Grievances and Pensions',
  'CENTRAL_AGENCY',
  'all, cpgrams, general civic grievances, central escalation, administrative reform',
  'Delhi',
  'New Delhi',
  'New Delhi',
  'New Delhi',
  'cpgrams-grievance@nic.in',
  '@DARPG_GoI',
  'https://pgportal.gov.in',
  'https://darpg.gov.in/whos-who',
  'VERIFIED',
  NOW(),
  true
);
